language: objective-c
osx_image: xcode8.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=VaultSDK.xcworkspace
    - IOS_FRAMEWORK_SCHEME="VaultSDK"
    - IOS_SDK=iphonesimulator10.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6S"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"

script:
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
